name: pinterest_app_clone
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.0
  http: ^0.13.4
  flutter_staggered_grid_view: ^0.6.1
  flutter_svg: ^1.0.3
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  url_launcher: ^6.0.20
  fluttertoast: ^8.0.8
  path_provider: ^2.0.9
  permission_handler: ^9.1.0
  lottie: ^1.2.2
  connectivity_plus: ^2.2.1
  dio: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/share_images/
    - assets/lottie/
  #   - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
